#!/bin/bash



# python train.py --batch_size 64 --model 'resnet50' --dataset 'OLIVES' --epochs 100 --device 'cuda:0' --train_image_path '/data/Datasets' --test_image_path '/home/kiran/Dropbox (GhassanGT)/Kiran/InSync/PhDResearch/Misc/' --test_csv_path './csv_dir/test_set_labels.csv' --train_csv_path './csv_dir/Training_Biomarker_Data.csv'


python train.py --batch_size 64 --model 'resnet50' --dataset 'OLIVES' --epochs 100 --device 'cuda:0' --train_image_path '/data/Datasets' --test_image_path '/home/kiran/Dropbox (GhassanGT)/Kiran/InSync/PhDResearch/Misc/' --test_csv_path './csv_dir/test_set_labels.csv' --train_csv_path './csv_dir/Training_Biomarker_Data.csv'


python GitHub\IEEE_SP_VGR\VIPCUP2023_OLIVES_with_Imagenet-main\train.py --batch_size 128 --model 'resnet50' --dataset 'OLIVES' --epochs 100 --device 'cuda:0' --train_image_path 'D:\Academics\Curricular Works\Semester_05\Data set\Train' --test_image_path 'D:\Academics\Curricular Works\Semester_05\Data set\TEST' --test_csv_path '"D:\Academics\Curricular Works\Semester_05\VSCode\IEEE SP cup\baseline_result.csv"' --train_csv_path "D:\Academics\Curricular Works\Semester_05\Data set\Train\Training_Biomarker_Data.csv"